# Numpy Library

In [ ]:
import numpy as np

In [ ]:
a = [1,2,3,4,5,6,7,8,9]
print(a)



[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
a[2]

3

In [ ]:
a+1 #integer can't be concanet with list but numpy array can


TypeError: can only concatenate list (not "int") to list

In [ ]:
for i in range(len(a)):
    a[i]+=1
print(a)

[2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a_np = np.array(a)
print(a_np)

[ 2  3  4  5  6  7  8  9 10]


In [ ]:
a_np

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a_np + 1 #here we can add integer to numpy array, not possible in List


array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
(a_np+1)[:5]

array([3, 4, 5, 6, 7])

In [ ]:
array_2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

array_2d[0]+1

array([2, 3, 4])

In [ ]:
array_2d.shape
array_2d.ndim

2

In [ ]:
a_num = np.array([1,2,3,4,5])

a_num.dtype

dtype('int64')

In [ ]:
array_2d = np.array([
    [1,2,3],
    [4,"hello",6],
    [7,8,9]
]
, dtype = np.float32)
array_2d.dtype   #string in array cause "<U21"


ValueError: could not convert string to float: 'hello'

In [ ]:
np.full((5,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [ ]:
ones = np.ones((5,5))
zeros = np.zeros((5,5))
print(ones)
print(zeros)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
ones * 6

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [ ]:
np.arange(10, 101, 10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
line = np.linspace(10,100,50)
print(line)

[ 10.          11.83673469  13.67346939  15.51020408  17.34693878
  19.18367347  21.02040816  22.85714286  24.69387755  26.53061224
  28.36734694  30.20408163  32.04081633  33.87755102  35.71428571
  37.55102041  39.3877551   41.2244898   43.06122449  44.89795918
  46.73469388  48.57142857  50.40816327  52.24489796  54.08163265
  55.91836735  57.75510204  59.59183673  61.42857143  63.26530612
  65.10204082  66.93877551  68.7755102   70.6122449   72.44897959
  74.28571429  76.12244898  77.95918367  79.79591837  81.63265306
  83.46938776  85.30612245  87.14285714  88.97959184  90.81632653
  92.65306122  94.48979592  96.32653061  98.16326531 100.        ]


In [ ]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]

a1 = np.array(l1)
print(a1)
a2 = np.array(l2)
print(a2)


[1 2 3 4 5]
[ 6  7  8  9 10]


# Operations with Array

In [ ]:
add = a1 + 5
multiply = a1 * 5
subtract = a1 - 1
Division = a1 / 2

print(add)
print(multiply)
print(subtract)
print(Division)

[ 6  7  8  9 10]
[ 5 10 15 20 25]
[0 1 2 3 4]
[0.5 1.  1.5 2.  2.5]


In [ ]:
a1 + 5 != a2

array([False, False, False, False, False])

In [ ]:
x = (a1+a2)*4   #Arithmetic operations of array in numpy is possible
print(x)

[28 36 44 52 60]


In [ ]:
a1_new = np.array([1,2,3,4,5])
a2_new = np.array([[6],[7]])

print(a1_new + a2_new)



[[ 7  8  9 10 11]
 [ 8  9 10 11 12]]


In [ ]:
np.sqrt(a1_new)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

# Rules of Broadcasting

Broadcasting follows a set of rules to determine the interaction between the two arrays:

1. **Dimension Compatibility**: Starting from the trailing dimensions, the dimensions of the arrays must either be the same, or one of them must be 1.
  
2. **Stretching**: If the sizes along a dimension are not the same, NumPy will try to stretch the array with size 1 along that dimension to match the other size.

3. **Result Shape**: The shape of the resulting array is the maximum size along each dimension from the input arrays.

### Scalar and One-dimensional Array


In [ ]:
# One dimensional Array:
import numpy as np

arr1d = np.array([1,2,3])
print("Array : ",arr1d)

res_arr = arr1d + 5

print("Result after adding 5: ",res_arr)

Array :  [1 2 3]
Result after adding 5:  [6 7 8]


In [ ]:
# Two dimensional Array:

arr2d = np.array([[1,2,3],[4,5,6]])
print("Array : ",arr2d)

res_arr2d = arr2d + 5

print("Result after adding 5: ",res_arr2d)

Array :  [[1 2 3]
 [4 5 6]]
Result after adding 5:  [[ 6  7  8]
 [ 9 10 11]]


In [ ]:
# Addition of two different dimensional array :-

print("One Dimensional Array: ",arr1d)
print("Two Dimensional Array: ",arr2d)

res_arr = arr1d + arr2d

print("\n Result of adding two different dimensional array : ",res_arr)



One Dimensional Array:  [1 2 3]
Two Dimensional Array:  [[1 2 3]
 [4 5 6]]

 Result of adding two different dimensional array :  [[2 4 6]
 [5 7 9]]


Broadcasting Two Arrays with Different Shapes

In [ ]:
A = np.array([[1,2],[3,4],[5,6]])

B = np.array([10,20])
print(f"Shape of array A is : {A.shape} \n Shape of array B is : {B.shape}")

A+B


Shape of array A is : (3, 2) 
 Shape of array B is : (2,)


array([[11, 22],
       [13, 24],
       [15, 26]])


## Practical Applications

1. **Data Normalization**: Broadcasting can be used to normalize datasets by subtracting the mean and dividing by the standard deviation.
  
2. **Image Manipulation**: You can use broadcasting to apply filters or adjustments to RGB channels in images.

3. **Mathematical Modeling**: In simulations or mathematical models, broadcasting can simplify the code and make it more efficient.

## Caveats and Limitations

1. **Implicitness**: Broadcasting can make code less explicit, which may lead to bugs if you're not careful about array shapes.

2. **Memory Efficiency**: While broadcasting saves memory by avoiding explicit replication of data, it's still possible to run into memory issues with very large arrays.


# Slicing of Arrays

Introduction

In [ ]:
# Part 1 : Basic Indexing

import numpy as np

exam_scores = np.array([90,85,77,94])

print("First student score: ",exam_scores[0])
print("Second student score: ",exam_scores[1])
print("Third student score: ",exam_scores[2])
print("Fourth student score: ",exam_scores[3])

First student score:  90
Second student score:  85
Third student score:  77
Fourth student score:  94


In [ ]:
# Part 2 : Multidimensional Indexing
# - Accessing elements in 2D and 3D arrays.
# - Using row and column indices.

sales_data = np.array([
    [200, 220, 250],
    [210, 230, 275],
    [190, 205, 235]
])

sales_data[2,1]

# sales_datax = np.array([
#     [[200, 220], 250, 300],
#     [210, 230, 275],
#     [190, 205, 235]
# ])

# sales_datax[2,1] ,,,,this is not working don't know why?


205

In [ ]:
# Part 3: Basic Silicing
# - How to slice arrays to get subarrays.
# - Using the 'start:stop:step' notation.

monthly_revenue = np.array([200,220,250,275,344,350,320,400,420,450,490])
monthly_revenue[3::2]


array([275, 350, 400, 450])

In [ ]:
# Part 4: Advanced Slicing Techniques

# - Using boolean arrays for indexing.
# - Combining slicing with conditional statements.

avg = np.mean(monthly_revenue)
print(avg)

monthly_revenue > avg

338.09090909090907


array([False, False, False, False,  True,  True, False,  True,  True,
        True,  True])

In [ ]:
# Part 5: Important Caveats and Best Practices
# -Mention that slices are views, not copies.
# -The importance of being aware of data types when slicing and indexing.




# Mini Project: 1D Slicing and Indexing with NumPy

## Objective

In this mini-project, you will practice 1D slicing and indexing techniques using NumPy. We'll work on a dataset that represents monthly sales data for a retail store and perform various data manipulation tasks.

## Dataset

Let's assume we have a 1D NumPy array that represents the monthly sales for a retail store for one year, in thousands of dollars.



In [ ]:
import numpy as np

monthly_sales = np.array([200, 220, 250, 275, 300, 320, 350, 370, 400, 420, 450, 475])

In [ ]:

# Tasks

# Task 1: Basic Indexing

# 1. Access and print the sales data for January (the first month).
# 2. Access and print the sales data for December (the last month).

print("sales data for January month: ",monthly_sales[0])

print("sales data for December month: ",monthly_sales[-1])



sales data for January month:  200
sales data for December month:  475


In [ ]:
# Task 2: Access Quarterly Data

# 1. Extract and print the sales data for each quarter (Q1, Q2, Q3, and Q4).

print("sales data for Q1(i.e Jan, Feb, Mar): ",monthly_sales[0:3])
print("sales data for Q2(i.e Apr, May, Jun): ",monthly_sales[3:6])
print("sales data for Q3(i.e Jul, Aug, Sep): ",monthly_sales[6:9])
print("sales data for Q4(i.e Oct, Nov, Dec): ",monthly_sales[9:12])





sales data for Q1(i.e Jan, Feb, Mar):  [200 220 250]
sales data for Q2(i.e Apr, May, Jun):  [275 300 320]
sales data for Q3(i.e Jul, Aug, Sep):  [350 370 400]
sales data for Q4(i.e Oct, Nov, Dec):  [420 450 475]


In [ ]:
# Task 3: Modify Sales Data

# 1. Assume that there was an error in the data entry for the month of April. The correct sales figure is $280,000. Update this value in the array.
# 2. Print the updated array to confirm the change.

monthly_sales[3] = 280
print(monthly_sales)



[200 220 250 280 300 320 350 370 400 420 450 475]


In [ ]:
# Task 4: Summer Sales

# 1. Extract and print the sales data for the summer months (June, July, August).
# 2. Calculate and print the average sales for the summer months.

print("sales data for June, July, Aug: ",monthly_sales[5:8])
Avg = np.mean(monthly_sales[5:8])
print("Average data of June, July, Aug: ",Avg)


sales data for June, July, Aug:  [320 350 370]
Average data of June, July, Aug:  346.6666666666667


In [ ]:
# Task 5: Above Average Months

# 1. Calculate the average monthly sales for the entire year.
# 2. Identify and print the months where the sales were above average.

avg_year = np.mean(monthly_sales)
print(avg_year)

print(monthly_sales > avg_year)



336.25
[False False False False False False  True  True  True  True  True  True]


# Python Loops vs Vectorization in NumPy

## Introduction









## Part 1: Understanding Python Loops

In [ ]:
daily_users = [200, 220, 250, 275]

avg_users = 0
for e in daily_users:
  avg_users += e

print(avg_users / len(daily_users))

236.25


## Part 2: Introduction to Vectorization
  - What vectorization is and why it's important.
  - Brief explanation of how NumPy uses vectorized operations.


In [ ]:
import numpy as np

du_np = np.array(daily_users)

print(np.mean(du_np))

236.25


## Part 3: Performance Comparison



In [ ]:
large_array = np.random.randint(1, 100, size=10000000)
large_array

array([45, 98, 82, ..., 80, 66, 47])

In [ ]:
import time

start_time = time.time()
avg = 0
for e in large_array:
  avg += e
print("Avg value using normal python: ",avg / 10000000)
end_time = time.time()
print("Time required to print Avg value using normal python:",end_time - start_time)

start_time = time.time()
print("Avg value using Numpy: ",np.mean(large_array))
end_time = time.time()
print("Time required to print Avg value using Numpy: ",end_time - start_time)


Avg value using normal python:  50.0011021
Time required to print Avg value using normal python: 2.6594133377075195
Avg value using Numpy:  50.0011021
Time required to print Avg value using Numpy:  0.015187740325927734


## Part 4: When to Use Loops and When to Use Vectorization


In [ ]:
filtered_users = []

for user_m in daily_users:
  if user_m > 200 and user_m % 2 == 0:
    filtered_users.append(user_m)

# Exercise: Vectorize a Given Python Loop

## Objective

In this exercise, you'll practice converting a Python loop that performs a mathematical operation into a vectorized version using NumPy. By doing so, you'll learn to write more efficient and cleaner code.

## Scenario

Imagine you're working with a dataset containing the monthly sales data for a retail business. You want to apply a 10% discount to each monthly sales figure to calculate the new sales numbers.



## Task 1: Using Python Loop

1. Create a list called `monthly_sales` containing 12 integers, each representing the sales for a month.
2. Initialize an empty list called `discounted_sales`.
3. Loop through each value in `monthly_sales`, apply a 10% discount, and append the result to `discounted_sales`.


In [ ]:
monthly_sales = [200, 220, 250, 275, 300, 320, 350, 370, 400, 420, 450, 470]

discounted_sales = []

for e in monthly_sales:
  discounted_sales.append(e * 0.9)

print(discounted_sales)

[180.0, 198.0, 225.0, 247.5, 270.0, 288.0, 315.0, 333.0, 360.0, 378.0, 405.0, 423.0]



## Task 2: Using NumPy Vectorization

### Instructions

1. Convert the `monthly_sales` list into a NumPy array.
2. Use NumPy's vectorized operations to apply a 10% discount to each value.
3. Store the result in a new NumPy array called `discounted_sales_np`.


In [ ]:
monthly_sales_np = np.array(monthly_sales)

discounted_sales_np = monthly_sales_np * 0.9

print(discounted_sales_np)

array([180. , 198. , 225. , 247.5, 270. , 288. , 315. , 333. , 360. ,
       378. , 405. , 423. ])

# Universal Functions - The Power of UFuncs in NumPy

## Introduction



## Part 1: What are UFuncs?
    - Definition and characteristics of UFuncs.
    - UFuncs allow for element-wise operations on arrays.













In [ ]:
import numpy as np

product_prices = np.array([20, 25, 33, 37, 40])

np.sqrt(product_prices)

array([4.47213595, 5.        , 5.74456265, 6.08276253, 6.32455532])

## Part 2: Basic UFuncs for Arithmetic Operations
    - Common arithmetic operations like addition, subtraction, multiplication, and division.


In [ ]:
revenue = np.array([4000, 4500, 4000])
expenses = np.array([2000, 1500, 2500])

print(np.subtract(revenue, expenses))
revenue - expenses

[2000 3000 1500]


array([2000, 3000, 1500])


## Part 3: Trigonometric and Logarithmic UFuncs
    - Trigonometric functions like `np.sin`, `np.cos`.
    - Logarithmic functions like `np.log`, `np.exp`.

In [ ]:
principal = 1000
rate = 0.05

years = np.array([1, 2, 3, 4, 5])

compound_interest = np.multiply(principal, np.exp(np.multiply(rate, years)))

print("compound interest value shall be: ",compound_interest)

compound interest value shall be:  [1051.27109638 1105.17091808 1161.83424273 1221.40275816 1284.02541669]


## Part 4: Comparison and Logical UFuncs

---


    - Comparison UFuncs like `np.greater`, `np.less_equal`.
    - Logical UFuncs like `np.logical_and`, `np.logical_or`.


In [ ]:
revenue = np.array([4000, 4500, 4000])
expenses = np.array([2000, 1500, 2500])
expenses[expenses <= 2000]

array([2000, 1500])

## Part 5: Custom UFuncs
    - Creating custom UFuncs using `np.vectorize`.


In [ ]:
def calculate_nps(score):
  if score >= 9:
    return "Promoter"
  elif score >= 7:
    return "Passive"
  else:
    return "Detractor"

nps_ufunc = np.vectorize(calculate_nps)

scores = np.array([9, 8, 6, 7, 6])
nps_ufunc(scores)

array(['Promoter', 'Passive', 'Detractor', 'Passive', 'Detractor'],
      dtype='<U9')

# Conditional Selection - Choosing with Conditions in NumPy

## Introduction

---

## Part 1: Basic Conditional Selection
- **Bullet Points**:
    - Introduction to the `np.where` function for basic conditional operations.
    - Real-world Example: Determining which employees are eligible for a bonus based on their performance scores.




In [ ]:
import numpy as np
scores = np.array([85, 90, 78, 92, 88])

eligibility = np.where(scores > 85, "Yes", "No")
eligibility

array(['No', 'Yes', 'No', 'Yes', 'Yes'], dtype='<U3')

## Part 2: Multiple Conditions
    - Using logical operators like `&` (and), `|` (or) to combine conditions.


In [ ]:
eligibility = np.where((scores < 87) & (scores > 80) | (scores > 90) , "Yes", "No")
eligibility

array(['Yes', 'No', 'No', 'Yes', 'No'], dtype='<U3')

## Part 3: Filtering Arrays
    - Using boolean indexing to filter arrays based on conditions.


In [ ]:
scores[(scores < 87) | (scores > 90)]

array([85, 78, 92])

## Part 4: Nested Conditions
    - Using nested `np.where` for more complex conditional logic.


In [ ]:
np.where(scores < 80 , "Yes", np.where(scores > 90 , "Yes", "No"))

array(['No', 'No', 'Yes', 'Yes', 'No'], dtype='<U3')

# Reshaping Arrays - Changing Dimensions and Size in NumPy

## Introduction

---





## Part 1: The `reshape` Method
    - Introduction to the `np.reshape` function for changing array dimensions.

In [ ]:
import numpy as np

data = np.random.randint(10, 100, 100)

data = data.reshape(10, 10)

data

array([[68, 98, 13, 24, 97, 21, 37, 39, 11, 15],
       [11, 28, 73, 28, 80, 68, 70, 92, 97, 84],
       [92, 53, 45, 62, 86, 30, 43, 24, 65, 34],
       [36, 91, 24, 82, 11, 41, 30, 92, 64, 79],
       [16, 98, 84, 58, 93, 57, 20, 48, 90, 26],
       [91, 17, 74, 45, 21, 62, 56, 43, 66, 94],
       [88, 72, 96, 21, 76, 19, 60, 84, 18, 51],
       [90, 30, 29, 45, 32, 90, 33, 97, 54, 65],
       [27, 37, 21, 21, 91, 59, 23, 33, 98, 47],
       [63, 90, 92, 89, 86, 74, 95, 42, 57, 33]])

## Part 2: Flattening Arrays
    - Using `ravel()` and `flatten()` to convert multi-dimensional arrays to 1D arrays.


In [ ]:
data2 = np.random.randint(10, 100, 25)
data2 = data2.reshape(5, 5)

data2.shape

(5, 5)

In [ ]:
data3 = data2.flatten()

data3[10] = 10000

print("data3: ",data3,"\n\n","data2: ",data2)


data3:  [   46    93    18    24    33    86    27    61    90    29 10000    99
    55    37    76    98    19    40    50    38    87    24    76    60
    91] 

 data2:  [[46 93 18 24 33]
 [86 27 61 90 29]
 [87 99 55 37 76]
 [98 19 40 50 38]
 [87 24 76 60 91]]


In [ ]:
data4 = data2.ravel()

data4[0] = 10_000

print("data4: ",data4,"\n\n","data2: ",data2)


data4:  [10000    93    18    24    33    86    27    61    90    29    87    99
    55    37    76    98    19    40    50    38    87    24    76    60
    91] 

 data2:  [[10000    93    18    24    33]
 [   86    27    61    90    29]
 [   87    99    55    37    76]
 [   98    19    40    50    38]
 [   87    24    76    60    91]]



## Part 3: Transposing Arrays
    - Using `np.transpose` or `.T` to swap array dimensions.



In [ ]:
data_T = np.random.randint(10, 100, 20).reshape(2, 10)

data_T = data_T.T

data_T

array([[52, 95],
       [18, 75],
       [82, 79],
       [27, 91],
       [74, 38],
       [73, 76],
       [40, 68],
       [75, 21],
       [73, 79],
       [19, 16]])

## Part 4: Resizing Arrays
    - Using `np.resize` to change the size of an array.



In [ ]:
np.resize(data_T, (5, 4))

array([[52, 95, 18, 75],
       [82, 79, 27, 91],
       [74, 38, 73, 76],
       [40, 68, 75, 21],
       [73, 79, 19, 16]])


## Part 5: Concatenating and Splitting Arrays
    - Using `np.concatenate`, `np.vstack`, and `np.hstack` for joining arrays.
    - Using `np.split` for breaking an array into smaller chunks.


In [ ]:
data_1t = np.array([100, 1500])
data_2t = np.array([200, 2500])

print("Concatenate function is used: ",np.concatenate((data_1t, data_2t)))
print("\n hstack function is used: ",np.hstack((data_1t, data_2t)))
print("\n vstack function is used: ",np.vstack((data_1t, data_2t)))



Concatenate function is used:  [ 100 1500  200 2500]

 hstack function is used:  [ 100 1500  200 2500]

 vstack function is used:  [[ 100 1500]
 [ 200 2500]]


# Handling Missing Values Using NumPy

## Introduction


## Part 1: Understanding Missing Values
    - Types of missing values: completely missing, partially missing, or incorrectly entered.
    - Common reasons for missing values: data entry errors, unavailability of information, etc.

In [ ]:
import numpy as np

customer_data = np.array([100, 150, np.nan, 200, 175])

## Part 2: Identifying Missing Values in NumPy
    - Using `np.isnan()` to identify missing values.
    - Counting the number of missing values in an array.



In [ ]:
missing_values = np.isnan(customer_data)

print("Missing value is: ",missing_values,"\n Number of missing values: ",np.sum(missing_values))


Missing value is:  [False False  True False False] 
 Number of missing values:  1


## Part 3: Replacing Missing Values
    - Using `np.nan_to_num()` to replace missing values with zero.
    - Replacing missing values with mean, median, or a specific value using `np.nanmean()` and `np.nanmedian()`.



In [ ]:
zero_filled = np.nan_to_num(customer_data)

zero_filled

mean_data = np.nanmean(customer_data)

data_mean_filled = np.where(np.isnan(customer_data), mean_data, customer_data)

data_mean_filled


array([100.  , 150.  , 156.25, 200.  , 175.  ])

## Part 4: Deleting Missing Values
    - Deleting rows with missing values using `np.isnan()` and array slicing.
    - When to delete data: caution about losing information.



In [ ]:
data_without_nan = customer_data[~np.isnan(customer_data)]
data_without_nan

array([100., 150., 200., 175.])

## Part 5: Forward and Backward Filling of Missing Values
    - Using methods to fill missing values based on neighboring elements.

In [ ]:
copy_of_cd = np.copy(customer_data)
mask = np.isnan(copy_of_cd)

copy_of_cd[mask] = np.roll(copy_of_cd, shift=-1)[mask]

copy_of_cd

array([100., 150., 200., 200., 175.])

# File Handling - Saving and Loading NumPy Arrays

## Introduction


---


## Part 1: Saving Arrays with `np.save` and `np.savez`
    - Introduction to the `np.save` function for saving single arrays.
    - Use of `np.savez` for saving multiple arrays.

In [ ]:
import numpy as np

age = np.array([18, 25, 33, 44, 22, 45])

np.save("age.npy", age)
age

array([18, 25, 33, 44, 22, 45])

## Part 2: Loading Arrays with `np.load`
    - Using the `np.load` function to load saved arrays.



In [ ]:
loaded_age = np.load("age.npy")
loaded_age

array([18, 25, 33, 44, 22, 45])

## Part 3: Saving Text Files with `np.savetxt`
    - Introduction to `np.savetxt` for saving arrays as text files.

In [ ]:
np.savetxt("age.txt", loaded_age, delimiter=",")

## Part 4: Loading Text Files with `np.loadtxt`
    - Using `np.loadtxt` to read text files and create arrays.



In [ ]:
new_age = np.loadtxt("age.txt", delimiter=",")
new_age

array([18., 25., 33., 44., 22., 45.])


## Part 5: Additional Options and Parameters
    - Discussion of additional parameters like `delimiter`, `skiprows`, and `usecols`.

